
class tts_language:
    def __init__(self) -> None:
        self.language = [
          {
        'tts': 'zh-CN-XiaoyiNeural',
        'Gender': 'Female',
        'country': '中国',
        'cn': '小艺',
        'whisper': 'zh-CN'
      },
      {
        'tts': 'zh-HK-WanLungNeural',
        'Gender': 'Male',
        'country': '中国香港',
        'cn': '云龙',
        'whisper': 'zh-CN'
      },
       {
        'tts': 'zh-HK-HiuMaanNeural',
        'Gender': 'Female',
        'country': '中国香港',
        'cn': '曉曼',
        'whisper': 'zh-CN'
      },
      {
        'tts': 'zh-CN-YunxiNeural',
        'Gender': 'Male',
        'country': '中国',
        'cn': '云曦',
        'whisper': 'zh-CN'
      },
      {
        'tts': 'zh-CN-liaoning-XiaobeiNeural',
        'Gender': 'Female',
        'country': '中国辽宁',
        'cn': '小贝',
        'whisper': 'zh-CN'
      },
       {
        'tts': 'zh-CN-liaoning-XiaobeiNeural',
        'Gender': 'Female',
        'country': '中国陕西',
        'cn': '小妮',
        'whisper': 'zh-CN'
      },
        {
        'tts': 'zh-TW-HsiaoChenNeural',
        'Gender': 'Female',
        'country': '中国台湾',
        'cn': '小陈',
        'whisper': 'zh-CN'
      },
         {
        'tts': 'zh-TW-YunJheNeural',
        'Gender': 'Male',
        'country': '中国台湾',
        'cn': '云哲',
        'whisper': 'zh-CN'
      },
        {
        'tts': 'zu-ZA-ThandoNeural',
        'Gender': 'Female',
        'country': '南非',
        'cn': '坦多',
        'whisper': 'Afrikaans'
      }, {
        'tts': 'zu-ZA-ThembaNeural',
        'Gender': 'Male',
        'country': '南非',
        'cn': '坦巴',
        'whisper': 'Afrikaans'
      }, {
        'tts': 'am-ET-AmehaNeural',
        'Gender': 'Male',
        'country': '埃塞俄比亚',
        'cn': '阿梅哈',
        'whisper': 'Amharic'
      }, {
        'tts': 'am-ET-MekdesNeural',
        'Gender': 'Female',
        'country': '埃塞俄比亚',
        'cn': '梅克德斯',
        'whisper': 'Amharic'
      }, {
        'tts': 'ar-EG-SalmaNeural',
        'Gender': 'Female',
        'country': '埃及',
        'cn': '萨尔玛',
        'whisper': 'Arabic'
      }, {
        'tts': 'ar-EG-ShakirNeural',
        'Gender': 'Male',
        'country': '埃及',
        'cn': '沙基尔',
        'whisper': 'Arabic'
      },
      {
        'tts': 'az-AZ-BabekNeural',
        'Gender': 'Male',
        'country': '阿塞拜疆',
        'cn': '巴贝克',
        'whisper': 'Azerbaijani'
      }, {
        'tts': 'az-AZ-BanuNeural',
        'Gender': 'Female',
        'country': '阿塞拜疆',
        'cn': '班努',
        'whisper': 'Azerbaijani'
      }, {
        'tts': 'bg-BG-BorislavNeural',
        'Gender': 'Male',
        'country': '保加利亚',
        'cn': '博里斯拉夫',
        'whisper': 'Bulgarian'
      }, {
        'tts': 'bg-BG-KalinaNeural',
        'Gender': 'Female',
        'country': '保加利亚',
        'cn': '卡琳娜',
        'whisper': 'Bulgarian'
      }, {
        'tts': 'bs-BA-GoranNeural',
        'Gender': 'Male',
        'country': '波斯尼亚和黑塞哥维那',
        'cn': '戈兰',
        'whisper': 'Bosnian'
      }, {
        'tts': 'bs-BA-VesnaNeural',
        'Gender': 'Female',
        'country': '波斯尼亚和黑塞哥维那',
        'cn': '维斯娜',
        'whisper': 'Bosnian'
      }, {
        'tts': 'es-ES-AlvaroNeural',
        'Gender': 'Male',
        'country': '西班牙',
        'cn': '阿尔瓦罗',
        'whisper': 'Catalan'
      }, {
        'tts': 'es-ES-ElviraNeural',
        'Gender': 'Female',
        'country': '西班牙',
        'cn': '埃尔维拉',
        'whisper': 'Catalan'
      }, 
      {
        'tts': 'cs-CZ-AntoninNeural',
        'Gender': 'Male',
        'country': '捷克',
        'cn': '安东宁',
        'whisper': 'Czech'
      }, {
        'tts': 'cs-CZ-VlastaNeural',
        'Gender': 'Female',
        'country': '捷克',
        'cn': '弗拉斯塔',
        'whisper': 'Czech'
      }, {
        'tts': 'cy-GB-AledNeural',
        'Gender': 'Male',
        'country': '威尔士',
        'cn': '阿利德',
        'whisper': 'Welsh'
      }, {
        'tts': 'cy-GB-NiaNeural',
        'Gender': 'Female',
        'country': '威尔士',
        'cn': '尼亚',
        'whisper': 'Welsh'
      }, {
        'tts': 'da-DK-ChristelNeural',
        'Gender': 'Female',
        'country': '丹麦',
        'cn': '克里斯特尔',
        'whisper': 'Danish'
      }, {
        'tts': 'da-DK-JeppeNeural',
        'Gender': 'Male',
        'country': '丹麦',
        'cn': '耶佩',
        'whisper': 'Danish'
      }, {
        'tts': 'de-DE-AmalaNeural',
        'Gender': 'Female',
        'country': '德国',
        'cn': '阿玛拉',
        'whisper': 'German'
      }, {
        'tts': 'de-DE-ConradNeural',
        'Gender': 'Male',
        'country': '德国',
        'cn': '康拉德',
        'whisper': 'German'
      }, {
        'tts': 'el-GR-AthinaNeural',
        'Gender': 'Female',
        'country': '希腊',
        'cn': '阿西娜',
        'whisper': 'Greek'
      }, {
        'tts': 'el-GR-NestorasNeural',
        'Gender': 'Male',
        'country': '希腊',
        'cn': '内斯托拉斯',
        'whisper': 'Greek'
      }, {
        'tts': 'en-US-AnaNeural',
        'Gender': 'Female',
        'country': '美国',
        'cn': '安娜',
        'whisper': 'English'
      }, {
        'tts': 'en-US-ChristopherNeural',
        'Gender': 'Male',
        'country': '美国',
        'cn': '克里斯托弗',
        'whisper': 'English'
      }, {
        'tts': 'et-EE-AnuNeural',
        'Gender': 'Female',
        'country': '爱沙尼亚',
        'cn': '阿努',
        'whisper': 'Estonian'
      }, {
        'tts': 'et-EE-KertNeural',
        'Gender': 'Male',
        'country': '爱沙尼亚',
        'cn': '科特',
        'whisper': 'Estonian'
      }, {
        'tts': 'fa-IR-DilaraNeural',
        'Gender': 'Female',
        'country': '伊朗',
        'cn': '迪拉拉',
        'whisper': 'Persian'
      }, {
        'tts': 'fa-IR-FaridNeural',
        'Gender': 'Male',
        'country': '伊朗',
        'cn': '法里德',
        'whisper': 'Persian'
      }, {
        'tts': 'fi-FI-HarriNeural',
        'Gender': 'Male',
        'country': '芬兰',
        'cn': '哈里',
        'whisper': 'Finnish'
      }, {
        'tts': 'fi-FI-NooraNeural',
        'Gender': 'Female',
        'country': '芬兰',
        'cn': '努拉',
        'whisper': 'Finnish'
      },
      {
        'tts': 'en-PH-JamesNeural',
        'Gender': 'Male',
        'country': '菲律宾',
        'cn': '詹姆斯',
        'whisper': 'tl'
      }, {
        'tts': 'en-PH-RosaNeural',
        'Gender': 'Female',
        'country': '菲律宾',
        'cn': '罗萨',
        'whisper': 'tl'
      }, {
        'tts': 'fr-FR-EloiseNeural',
        'Gender': 'Female',
        'country': '法国',
        'cn': '埃洛伊塞',
        'whisper': 'French'
      }, {
        'tts': 'en-NG-AbeoNeural',
        'Gender': 'Male',
        'country': '尼日利亚',
        'cn': '阿贝奥',
        'whisper': 'Hausa'
      }, {
        'tts': 'en-NG-EzinneNeural',
        'Gender': 'Female',
        'country': '尼日利亚',
        'cn': '埃津内',
        'whisper': 'Hausa'
      }, {
        'tts': 'he-IL-AvriNeural',
        'Gender': 'Male',
        'country': '以色列',
        'cn': '阿夫里',
        'whisper': 'Hebrew'
      }, {
        'tts': 'he-IL-HilaNeural',
        'Gender': 'Female',
        'country': '以色列',
        'cn': '希拉',
        'whisper': 'Hebrew'
      }, {
        'tts': 'hr-HR-GabrijelaNeural',
        'Gender': 'Female',
        'country': '克罗地亚',
        'cn': '加布里埃拉',
        'whisper': 'Croatian'
      }, {
        'tts': 'hr-HR-SreckoNeural',
        'Gender': 'Male',
        'country': '克罗地亚',
        'cn': '斯雷科',
        'whisper': 'Croatian'
      }, {
        'tts': 'hu-HU-NoemiNeural',
        'Gender': 'Female',
        'country': '匈牙利',
        'cn': '诺埃米',
        'whisper': 'Hungarian'
      }, {
        'tts': 'hu-HU-TamasNeural',
        'Gender': 'Male',
        'country': '匈牙利',
        'cn': '塔马斯',
        'whisper': 'Hungarian'
      }, {
        'tts': 'id-ID-ArdiNeural',
        'Gender': 'Male',
        'country': '印度尼西亚',
        'cn': '阿尔迪',
        'whisper': 'Indonesian'
      }, {
        'tts': 'id-ID-GadisNeural',
        'Gender': 'Female',
        'country': '印度尼西亚',
        'cn': '加蒂斯',
        'whisper': 'Indonesian'
      }, {
        'tts': 'is-IS-GudrunNeural',
        'Gender': 'Female',
        'country': '冰岛',
        'cn': '古德伦',
        'whisper': 'Icelandic'
      }, {
        'tts': 'is-IS-GunnarNeural',
        'Gender': 'Male',
        'country': '冰岛',
        'cn': '冈纳尔',
        'whisper': 'Icelandic'
      }, {
        'tts': 'it-IT-DiegoNeural',
        'Gender': 'Male',
        'country': '意大利',
        'cn': '迭戈',
        'whisper': 'Italian'
      }, {
        'tts': 'it-IT-ElsaNeural',
        'Gender': 'Female',
        'country': '意大利',
        'cn': '艾尔莎',
        'whisper': 'Italian'
      }, {
        'tts': 'ja-JP-KeitaNeural',
        'Gender': 'Male',
        'country': '日本',
        'cn': '敬太',
        'whisper': 'Japanese'
      }, {
        'tts': 'ja-JP-NanamiNeural',
        'Gender': 'Female',
        'country': '日本',
        'cn': '七海',
        'whisper': 'Japanese'
      }, {
        'tts': 'ka-GE-EkaNeural',
        'Gender': 'Female',
        'country': '格鲁吉亚',
        'cn': '艾卡',
        'whisper': 'Georgian'
      }, {
        'tts': 'ka-GE-GiorgiNeural',
        'Gender': 'Male',
        'country': '格鲁吉亚',
        'cn': '乔治',
        'whisper': 'Georgian'
      }, {
        'tts': 'kk-KZ-AigulNeural',
        'Gender': 'Female',
        'country': '哈萨克斯坦',
        'cn': '艾古丽',
        'whisper': 'Kazakh'
      }, {
        'tts': 'kk-KZ-DauletNeural',
        'Gender': 'Male',
        'country': '哈萨克斯坦',
        'cn': '达乌列特',
        'whisper': 'Kazakh'
      }, {
        'tts': 'km-KH-PisethNeural',
        'Gender': 'Male',
        'country': '柬埔寨',
        'cn': '皮塞特',
        'whisper': 'Khmer'
      }, {
        'tts': 'km-KH-SreymomNeural',
        'Gender': 'Female',
        'country': '柬埔寨',
        'cn': '斯雷莫',
        'whisper': 'Khmer'
      }, {
        'tts': 'ko-KR-InJoonNeural',
        'Gender': 'Male',
        'country': '韩国',
        'cn': '仁俊',
        'whisper': 'Korean'
      }, {
        'tts': 'ko-KR-SunHiNeural',
        'Gender': 'Female',
        'country': '韩国',
        'cn': '善熙',
        'whisper': 'Korean'
      }, {
        'tts': 'lo-LA-ChanthavongNeural',
        'Gender': 'Male',
        'country': '老挝',
        'cn': '查塔旺',
        'whisper': 'Lao'
      }, {
        'tts': 'lo-LA-KeomanyNeural',
        'Gender': 'Female',
        'country': '老挝',
        'cn': '科曼尼',
        'whisper': 'Lao'
      }, {
        'tts': 'lt-LT-LeonasNeural',
        'Gender': 'Male',
        'country': '立陶宛',
        'cn': '莱昂纳斯',
        'whisper': 'Lithuanian'
      }, {
        'tts': 'lt-LT-OnaNeural',
        'Gender': 'Female',
        'country': '立陶宛',
        'cn': '奥娜',
        'whisper': 'Lithuanian'
      }, {
        'tts': 'lv-LV-EveritaNeural',
        'Gender': 'Female',
        'country': '拉脱维亚',
        'cn': '埃维里塔',
        'whisper': 'Latvian'
      }, {
        'tts': 'lv-LV-NilsNeural',
        'Gender': 'Male',
        'country': '拉脱维亚',
        'cn': '尼尔斯',
        'whisper': 'Latvian'
      }, {
        'tts': 'en-NZ-MitchellNeural',
        'Gender': 'Male',
        'country': '新西兰',
        'cn': '米切尔',
        'whisper': 'Maori'
      }, {
        'tts': 'en-NZ-MollyNeural',
        'Gender': 'Female',
        'country': '新西兰',
        'cn': '莫莉',
        'whisper': 'Maori'
      }, {
        'tts': 'mn-MN-BataaNeural',
        'Gender': 'Male',
        'country': '蒙古',
        'cn': '巴塔',
        'whisper': 'Mongolian'
      }, {
        'tts': 'mn-MN-YesuiNeural',
        'Gender': 'Female',
        'country': '蒙古',
        'cn': '耶苏伊',
        'whisper': 'Mongolian'
      }, {
        'tts': 'ms-MY-OsmanNeural',
        'Gender': 'Male',
        'country': '马来西亚',
        'cn': '奥斯曼',
        'whisper': 'Malay'
      }, {
        'tts': 'ms-MY-YasminNeural',
        'Gender': 'Female',
        'country': '马来西亚',
        'cn': '亚斯敏',
        'whisper': 'Malay'
      }, {
        'tts': 'mt-MT-GraceNeural',
        'Gender': 'Female',
        'country': '马耳他',
        'cn': '格蕾丝',
        'whisper': 'Maltese'
      }, {
        'tts': 'mt-MT-JosephNeural',
        'Gender': 'Male',
        'country': '马耳他',
        'cn': '约瑟夫',
        'whisper': 'Maltese'
      },
      {
        'tts': 'my-MM-NilarNeural',
        'Gender': 'Female',
        'country': '缅甸',
        'cn': '尼拉',
        'whisper': 'my'
      }, {
        'tts': 'my-MM-ThihaNeural',
        'Gender': 'Male',
        'country': '缅甸',
        'cn': '蒂哈',
        'whisper': 'my'
      }, {
        'tts': 'ne-NP-HemkalaNeural',
        'Gender': 'Female',
        'country': '尼泊尔',
        'cn': '赫姆卡拉',
        'whisper': 'Nepali'
      }, {
        'tts': 'ne-NP-SagarNeural',
        'Gender': 'Male',
        'country': '尼泊尔',
        'cn': '萨加尔',
        'whisper': 'Nepali'
      }, {
        'tts': 'nl-NL-FennaNeural',
        'Gender': 'Female',
        'country': '荷兰',
        'cn': '芬娜',
        'whisper': 'Dutch'
      }, {
        'tts': 'nl-NL-MaartenNeural',
        'Gender': 'Male',
        'country': '荷兰',
        'cn': '马尔滕',
        'whisper': 'Dutch'
      }, {
        'tts': 'fr-FR-EloiseNeural',
        'Gender': 'Female',
        'country': '法国',
        'cn': '埃洛伊塞',
        'whisper': 'French'
      }, {
        'tts': 'fr-FR-HenriNeural',
        'Gender': 'Male',
        'country': '法国',
        'cn': '亨利',
        'whisper': 'French'
      }, {
        'tts': 'pl-PL-MarekNeural',
        'Gender': 'Male',
        'country': '波兰',
        'cn': '马雷克',
        'whisper': 'Polish'
      }, {
        'tts': 'pl-PL-ZofiaNeural',
        'Gender': 'Female',
        'country': '波兰',
        'cn': '佐菲亚',
        'whisper': 'Polish'
      }, {
        'tts': 'ps-AF-GulNawazNeural',
        'Gender': 'Male',
        'country': '阿富汗',
        'cn': '古尔纳瓦兹',
        'whisper': 'Pashto'
      }, {
        'tts': 'ps-AF-LatifaNeural',
        'Gender': 'Female',
        'country': '阿富汗',
        'cn': '拉蒂法',
        'whisper': 'Pashto'
      }, {
        'tts': 'pt-BR-AntonioNeural',
        'Gender': 'Male',
        'country': '巴西',
        'cn': '安东尼奥',
        'whisper': 'Portuguese'
      }, {
        'tts': 'pt-BR-FranciscaNeural',
        'Gender': 'Female',
        'country': '巴西',
        'cn': '弗朗西斯卡',
        'whisper': 'Portuguese'
      }, {
        'tts': 'ro-RO-AlinaNeural',
        'Gender': 'Female',
        'country': '罗马尼亚',
        'cn': '阿丽娜',
        'whisper': 'Romanian'
      }, {
        'tts': 'ro-RO-EmilNeural',
        'Gender': 'Male',
        'country': '罗马尼亚',
        'cn': '埃米尔',
        'whisper': 'Romanian'
      }, {
        'tts': 'ru-RU-DmitryNeural',
        'Gender': 'Male',
        'country': '俄罗斯',
        'cn': '德米特里',
        'whisper': 'Russian'
      }, {
        'tts': 'ru-RU-SvetlanaNeural',
        'Gender': 'Female',
        'country': '俄罗斯',
        'cn': '斯韦特兰娜',
        'whisper': 'Russian'
      }, {
        'tts': 'ur-PK-AsadNeural',
        'Gender': 'Male',
        'country': '巴基斯坦',
        'cn': '阿萨德',
        'whisper': 'Sindhi'
      }, {
        'tts': 'ur-PK-UzmaNeural',
        'Gender': 'Female',
        'country': '巴基斯坦',
        'cn': '乌兹玛',
        'whisper': 'Sindhi'
      }, {
        'tts': 'sk-SK-LukasNeural',
        'Gender': 'Male',
        'country': '斯洛伐克',
        'cn': '卢卡斯',
        'whisper': 'Slovak'
      }, {
        'tts': 'sk-SK-ViktoriaNeural',
        'Gender': 'Female',
        'country': '斯洛伐克',
        'cn': '维多利亚',
        'whisper': 'Slovak'
      }, {
        'tts': 'sl-SI-PetraNeural',
        'Gender': 'Female',
        'country': '斯洛文尼亚',
        'cn': '佩特拉',
        'whisper': 'Slovenian'
      }, {
        'tts': 'sl-SI-RokNeural',
        'Gender': 'Male',
        'country': '斯洛文尼亚',
        'cn': '罗克',
        'whisper': 'Slovenian'
      }, {
        'tts': 'so-SO-MuuseNeural',
        'Gender': 'Male',
        'country': '索马里',
        'cn': '穆塞',
        'whisper': 'Somali'
      }, {
        'tts': 'so-SO-UbaxNeural',
        'Gender': 'Female',
        'country': '索马里',
        'cn': '乌巴克斯',
        'whisper': 'Somali'
      }, {
        'tts': 'sr-RS-NicholasNeural',
        'Gender': 'Male',
        'country': '塞尔维亚',
        'cn': '尼古拉斯',
        'whisper': 'Serbian'
      }, {
        'tts': 'sr-RS-SophieNeural',
        'Gender': 'Female',
        'country': '塞尔维亚',
        'cn': '索菲',
        'whisper': 'Serbian'
      }, {
        'tts': 'sv-SE-MattiasNeural',
        'Gender': 'Male',
        'country': '瑞典',
        'cn': '马蒂亚斯',
        'whisper': 'Swedish'
      }, {
        'tts': 'sv-SE-SofieNeural',
        'Gender': 'Female',
        'country': '瑞典',
        'cn': '索菲',
        'whisper': 'Swedish'
      }, {
        'tts': 'en-KE-AsiliaNeural',
        'Gender': 'Female',
        'country': '肯尼亚',
        'cn': '阿西莉亚',
        'whisper': 'Swahili'
      }, {
        'tts': 'en-KE-ChilembaNeural',
        'Gender': 'Male',
        'country': '肯尼亚',
        'cn': '奇莱姆巴',
        'whisper': 'Swahili'
      }, {
        'tts': 'th-TH-NiwatNeural',
        'Gender': 'Male',
        'country': '泰国',
        'cn': '尼瓦特',
        'whisper': 'Thai'
      }, {
        'tts': 'th-TH-PremwadeeNeural',
        'Gender': 'Female',
        'country': '泰国',
        'cn': '普雷姆瓦迪',
        'whisper': 'Thai'
      }, {
        'tts': 'tr-TR-AhmetNeural',
        'Gender': 'Male',
        'country': '土耳其',
        'cn': '艾哈迈德',
        'whisper': 'Turkish'
      }, {
        'tts': 'tr-TR-EmelNeural',
        'Gender': 'Female',
        'country': '土耳其',
        'cn': '艾梅尔',
        'whisper': 'Turkish'
      }, {
        'tts': 'uk-UA-OstapNeural',
        'Gender': 'Male',
        'country': '乌克兰',
        'cn': '奥斯塔普',
        'whisper': 'Ukrainian'
      }, {
        'tts': 'uk-UA-PolinaNeural',
        'Gender': 'Female',
        'country': '乌克兰',
        'cn': '波利娜',
        'whisper': 'Ukrainian'
      }, {
        'tts': 'ur-PK-AsadNeural',
        'Gender': 'Male',
        'country': '巴基斯坦',
        'cn': '阿萨德',
        'whisper': 'Sindhi'
      }, {
        'tts': 'ur-PK-UzmaNeural',
        'Gender': 'Female',
        'country': '巴基斯坦',
        'cn': '乌兹玛',
        'whisper': 'Sindhi'
      }, {
        'tts': 'uz-UZ-MadinaNeural',
        'Gender': 'Female',
        'country': '乌兹别克斯坦',
        'cn': '玛迪娜',
        'whisper': 'Uzbek'
      }, {
        'tts': 'uz-UZ-SardorNeural',
        'Gender': 'Male',
        'country': '乌兹别克斯坦',
        'cn': '萨尔多尔',
        'whisper': 'Uzbek'
      }, 
      {
        'tts': 'vi-VN-HoaiMyNeural',
        'Gender': 'Female',
        'country': '越南',
        'cn': '怀美',
        'whisper': 'vi'
      }, {
        'tts': 'vi-VN-NamMinhNeural',
        'Gender': 'Male',
        'country': '越南',
        'cn': '南明',
        'whisper': 'vi'
      }, {
        'tts': 'en-NG-AbeoNeural',
        'Gender': 'Male',
        'country': '尼日利亚',
        'cn': '阿贝奥',
        'whisper': 'Hausa'
      }, {
        'tts': 'en-NG-EzinneNeural',
        'Gender': 'Female',
        'country': '尼日利亚',
        'cn': '埃津内',
        'whisper': 'Hausa'
      }]

ttsLanguageMgr = tts_language()        